### ISSUE TITLE
Error while grouping rows in datagrid

### ISSUE THREAD

**Issue by rohit3d2003** [ButchersBoy/MaterialDesignInXamlToolkit#366]
I am trying to group using ListViewCollection on Name of employee and everything works fine for the first time. When I go to a different view and come back to the same view, the code is throwing an error as mentioned below. I am using MVVM light libs to have single instance of my viewmodel.

If I remove the Expander from the group style then everything works fine.

<DataGrid Grid.Row="1" Grid.Column="0" Margin="10,15,10,0"
                  ItemsSource="{Binding Path=VacationsCollectionView}"
                  CanUserAddRows="False"
                  CanUserDeleteRows="False"
                  HorizontalAlignment="Stretch"
                  AutoGenerateColumns="False"
                  IsReadOnly="True"
                  HorizontalScrollBarVisibility="Disabled"
                  materialDesign:DataGridAssist.CellPadding="4 2 2 2"
                  materialDesign:DataGridAssist.ColumnHeaderPadding="4 2 2 2">
            <DataGrid.GroupStyle>
                <GroupStyle>
                    <GroupStyle.ContainerStyle>
                        <Style TargetType="{x:Type GroupItem}">
                            <Setter Property="Template">
                                <Setter.Value>
                                    <ControlTemplate TargetType="{x:Type GroupItem}">
                                        <Expander BorderThickness="1">
                                            <Expander.Header>
                                                <TextBlock Text="{Binding Name}"
                                                           Style="{StaticResource MaterialDesignBody2TextBlock}" />
                                            </Expander.Header>
                                            <ItemsPresenter />
                                        </Expander>
                                    </ControlTemplate>
                                </Setter.Value>
                            </Setter>
                        </Style>
                    </GroupStyle.ContainerStyle>
                </GroupStyle>
            </DataGrid.GroupStyle>
            <DataGrid.Columns>
                <DataGridTemplateColumn Header="Delete">
                    <DataGridTemplateColumn.CellTemplate>
                        <DataTemplate>
                            <Button ToolTip="Delete" Style="{StaticResource MaterialDesignFlatButton}"
                                    Padding="2,2,2,2"
                                    Command="{Binding DataContext.DeleteVacationCommand, ElementName=VacationViewControl}"
                                    Height="18">
                                <materialDesign:PackIcon Kind="Delete" Width="15" Height="15" />
                            </Button>
                        </DataTemplate>
                    </DataGridTemplateColumn.CellTemplate>
                </DataGridTemplateColumn>
                <materialDesign:MaterialDataGridTextColumn Header="Vacation Type" MinWidth="100"
                                                           Binding="{Binding Path=VacationType, Converter={StaticResource EnumConverter}}" />
                <materialDesign:MaterialDataGridTextColumn Header="Start Date" MinWidth="100"
                                                           Binding="{Binding Path=StartDate, StringFormat='MMM dd, yyyy'}" />
                <materialDesign:MaterialDataGridTextColumn Header="End Date" MinWidth="100"
                                                           Binding="{Binding Path=EndDate, StringFormat='MMM dd, yyyy'}" />
                <materialDesign:MaterialDataGridTextColumn Header="Days" MinWidth="100"
                                                           Binding="{Binding Path=NumberOfDays}" />
            </DataGrid.Columns>
        </DataGrid>

Error - 
System.InvalidOperationException was unhandled
  HResult=-2146233079
  Message=The specified Visual is not an ancestor of this Visual.
  Source=PresentationCore
  StackTrace:
       at System.Windows.Media.Visual.TrySimpleTransformToAncestor(Visual ancestor, Boolean inverse, GeneralTransform& generalTransform, Matrix& simpleTransform)
       at System.Windows.Media.Visual.TransformToAncestor(Visual ancestor)
       at System.Windows.Controls.DataGridCellsPanel.ComputeCellsPanelHorizontalOffset()
       at System.Windows.Controls.DataGridHelper.GetParentCellsPanelHorizontalOffset(IProvideDataGridColumn cell)
       at System.Windows.Controls.DataGrid.InvalidateCellsPanelHorizontalOffset(Object args)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.DispatcherOperation.InvokeImpl()
       at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Windows.Threading.DispatcherOperation.Invoke()
       at System.Windows.Threading.Dispatcher.ProcessQueue()
       at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
       at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
       at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
       at System.Windows.Application.RunDispatcher(Object ignore)
       at System.Windows.Application.RunInternal(Window window)
       at System.Windows.Application.Run(Window window)
       at System.Windows.Application.Run()
       at Paragon.App.Main() in C:\Projects\Paragon\Paragon\obj\Debug\App.g.cs:line 0
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException:

**Comment by ButchersBoy** [comment]
Have you tried this without MD styles applied?

Can you post a  test repo please.

**Comment by rohit3d2003** [comment]
After removing the MD styles on datagrid, I can still reproduce this error. I am using MahApps.Metro along with MD styles in my application. The bound collection is a simple object with Name, StartDate, EndDate and NumberOfDays in it and I am grouping the collection on the Name property. I have also added a template column in datagrid which contains a button with Delete image to allow deletion of individual record

**Comment by ButchersBoy** [comment]
So this isn't a MD Toolkit error?

**Comment by rohit3d2003** [comment]
I am not entirely sure since entire application uses MD but based on the error it seems like it is only related to datagrid and removing the MD style from datagrid didn't resolve this issue

**Comment by rohit3d2003** [comment]
I can try to solve this by using ListView but I don't see a MD style which I can use for the same

**Comment by ButchersBoy** [comment]
I think you're going to have to post a test repository with repeatable steps.
