### ISSUE TITLE
InvalidOperationException was unhandled when changing Primary Color

### ISSUE THREAD

**Issue by neomaximus2k** [ButchersBoy/MaterialDesignInXamlToolkit#577]
I am attempting to change the primary colour of the application to lime through code.

I have the following code:
```
        private void Button_Click(object sender, RoutedEventArgs e)
        {
            var Swatches = new SwatchesProvider().Swatches;

            var swatch = new SwatchesProvider().Swatches.FirstOrDefault(
                s => string.Compare(s.Name, "lime", StringComparison.InvariantCultureIgnoreCase) == 0);
            //ReplacePrimaryColor(swatch);

            if (swatch == null) throw new ArgumentNullException(nameof(swatch));
            new PaletteHelper().ReplacePrimaryColor(swatch);
        }
```
The error throws on the new PaletteHelper() call

```
System.InvalidOperationException was unhandled
  HResult=-2146233079
  Message=Sequence contains more than one matching element
  Source=System.Core
  StackTrace:
       at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
       at MaterialDesignThemes.Wpf.PaletteHelper.GetBrush(String name) in C:\projects\materialdesigninxamltoolkit\MaterialDesignThemes.Wpf\PaletteHelper.cs:line 210
       at MaterialDesignThemes.Wpf.PaletteHelper.QueryPalette() in C:\projects\materialdesigninxamltoolkit\MaterialDesignThemes.Wpf\PaletteHelper.cs:line 142
       at MaterialDesignThemes.Wpf.PaletteHelper.ReplacePrimaryColor(Swatch swatch) in C:\projects\materialdesigninxamltoolkit\MaterialDesignThemes.Wpf\PaletteHelper.cs:line 71
```

**Comment by ButchersBoy** [comment]
I've seen people have this before when their App.xaml is configured incorrectly.  What does you App.xaml look like?

**Comment by neomaximus2k** [comment]
@ButchersBoy  thanks for that, it appears the resource was loaded in twice for a single colour! *bangs head on desk*
